name: fitness_memo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0-dev.5
  table_calendar: ^3.0.0
  drift: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  drift_dev: ^2.0.1

flutter:
  uses-material-design: true
 